# Generated by Django 5.0 on 2023-12-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserNotificationSetting',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
