# Generated by Django 5.0 on 2023-12-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('api_category', models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3')], max_length=20)),
            ],
        ),
    ]
