# Generated by Django 5.0 on 2023-12-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountform',
            unique_together={('api_category',)},
        ),
        migrations.CreateModel(
            name='RetailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20)),
                ('increase_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('api_category', models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3')], max_length=20)),
            ],
            options={
                'unique_together': {('api_category',)},
            },
        ),
    ]
