# Generated by Django 4.2.6 on 2024-01-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_discountform_unique_together_retailprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('departure', models.DateTimeField()),
                ('product_thumbnail', models.URLField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('api_category', models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3')], max_length=20)),
                ('reservation_id', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='retailprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discountform',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage')], max_length=20),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.booking')),
            ],
        ),
    ]
