# Generated by Django 4.2.6 on 2024-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_price_alter_tour_options_remove_tour_price_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
