# Generated by Django 4.2.6 on 2024-01-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_tour_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_schedules', to='shop.tourschedule'),
        ),
    ]
