# Generated by Django 4.2.6 on 2024-01-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_tour_tour_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_schedule',
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='tour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='available_days',
            field=models.ManyToManyField(related_name='schedules', to='shop.day'),
        ),
    ]
