# Generated by Django 4.2.6 on 2024-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_tour_tour_schedule_tourschedule_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='api_category',
            field=models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3'), ('G', 'GLT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discountform',
            name='api_category',
            field=models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3'), ('G', 'GLT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retailprice',
            name='api_category',
            field=models.CharField(choices=[('V', 'Ventrata'), ('T', 'Tour CMS'), ('B', 'Bokun'), ('W', 'Wave3'), ('G', 'GLT')], max_length=20),
        ),
    ]
