# Generated by Django 4.2.6 on 2024-01-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_booking_api_category_alter_booking_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.CharField(max_length=10),
        ),
    ]
