# Generated by Django 4.2.6 on 2024-01-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_booking_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product_thumbnail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='shop.booking'),
        ),
    ]
