# Generated by Django 4.2.6 on 2024-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
