# Generated by Django 4.2.6 on 2024-01-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_participant_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
