# Generated by Django 4.2.6 on 2024-02-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticket_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
