# Generated by Django 4.2.6 on 2024-02-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_booking_ticket_booking_ticket_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
