# Generated by Django 4.2.6 on 2024-02-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_booking_departure_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
