# Generated by Django 4.2.6 on 2024-03-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_searchcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTicketOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_options', to='shop.tour')),
            ],
            options={
                'verbose_name': 'Tour Ticket Option',
                'verbose_name_plural': 'Tour Ticket Options',
            },
        ),
    ]
