# Generated by Django 4.2.6 on 2024-03-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_tourticketoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
