# Generated by Django 4.2.6 on 2024-03-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_price_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='capacity',
        ),
    ]
