# Generated by Django 4.2.6 on 2024-03-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_price_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
