# Generated by Django 4.2.6 on 2024-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_booking_ticket_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ticket_options',
            field=models.ManyToManyField(related_name='ticket_options', to='shop.tourticketoptions'),
        ),
    ]
