# Generated by Django 4.2.6 on 2024-03-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_price_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='ticket_options',
        ),
        migrations.AddField(
            model_name='tourticketoptions',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option_price', to='shop.price'),
            preserve_default=False,
        ),
    ]
