# Generated by Django 4.2.6 on 2024-03-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_price_ticket_options_tourticketoptions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourticketoptions',
            name='tour',
        ),
    ]
