# Generated by Django 4.2.6 on 2024-03-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_tourticketoptions_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_option',
        ),
        migrations.DeleteModel(
            name='TourTicketOptions',
        ),
    ]
