# Generated by Django 4.2.6 on 2024-03-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_optionprice_booking_option_name_price_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionPrice',
            new_name='PriceOption',
        ),
    ]
