# Generated by Django 4.2.6 on 2024-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_rename_optionprice_priceoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='option_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='option_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
