# Generated by Django 4.2.6 on 2024-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
