# Generated by Django 4.2.6 on 2024-03-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_booking_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_used',
            new_name='is_valid',
        ),
    ]
