# Generated by Django 4.2.6 on 2024-03-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_rename_is_used_booking_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_checker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
