# Generated by Django 4.2.6 on 2024-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_booking_ticket_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ticket_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
