# Generated by Django 4.2.6 on 2024-04-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_tour_ticket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('backgroundColor', models.CharField(max_length=50)),
                ('liteBg', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviewcards', to='shop.tour')),
            ],
        ),
    ]
