# Generated by Django 4.2.6 on 2025-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_salepoint_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchcategory',
            options={'verbose_name': 'Search Category', 'verbose_name_plural': 'Search Categories'},
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
