# Generated by Django 4.2.6 on 2025-02-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_searchcategory_options_tour_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255)),
                ('validFor', models.CharField(max_length=255)),
                ('activationMethod', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HopOnHopOffTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeInformation', models.TextField()),
                ('ticketType', models.CharField(max_length=255)),
                ('operatingHours', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageType', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('category', models.CharField(max_length=255)),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('description', models.TextField()),
                ('basePrice', models.CharField(max_length=255)),
                ('cancellationPolicy', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('contactInformation', models.TextField()),
                ('termsAndConditions', models.TextField()),
                ('bookingInformation', models.TextField()),
                ('isBlocked', models.BooleanField(default=False)),
                ('isFoodIncluded', models.BooleanField(default=False)),
                ('isTransportIncluded', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferType', models.CharField(max_length=255)),
                ('pickupLocation', models.CharField(max_length=255)),
                ('dropoffLocation', models.CharField(max_length=255)),
                ('vehicleType', models.CharField(max_length=255)),
                ('luggageAllowance', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tour1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourType', models.CharField(max_length=255)),
                ('locationsCovered', models.TextField()),
                ('guideInformation', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeRange', models.CharField(max_length=255)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='shop.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Summarize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryText', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarize', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalItemName', models.CharField(max_length=255)),
                ('rentalType', models.CharField(max_length=255)),
                ('rentalPeriod', models.CharField(max_length=255)),
                ('ageRequirement', models.CharField(blank=True, max_length=255, null=True)),
                ('damagePolicy', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('cityCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptionPoints', to='shop.citycard')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTimeSlotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('dynamicPrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTimeSlotPrices', to='shop.dynamicprice')),
            ],
        ),
        migrations.CreateModel(
            name='PickupDropoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('hopOnHopOffTicket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupDropoffPoints', to='shop.hoponhopoffticket')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupDropoffs', to='shop.product')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupDropoffPoints', to='shop.tour1')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(max_length=255)),
                ('activityName', models.CharField(max_length=255)),
                ('specialRequirements', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otherCategory', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='NotSuitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notSuitable', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='NotAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notAllowed', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='MustCarryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mustCarryItems', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productKeywords', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='InclusionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='hoponhopoffticket',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hopOnHopOffTicket', to='shop.product'),
        ),
        migrations.CreateModel(
            name='ExclusionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencyContacts', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='dynamicprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarWisePricing', to='shop.product'),
        ),
        migrations.AddField(
            model_name='citycard',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cityCard', to='shop.product'),
        ),
        migrations.AddField(
            model_name='availability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='shop.product'),
        ),
        migrations.CreateModel(
            name='AttractionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(max_length=255)),
                ('ageRestrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('accessibility', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attractionTicket', to='shop.product')),
            ],
        ),
    ]
