# Generated by Django 4.2.6 on 2025-02-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_availability_citycard_dynamicprice_hoponhopoffticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('option', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval_mins', models.PositiveIntegerField()),
                ('available_days', models.ManyToManyField(related_name='product_schedules', to='shop.day')),
            ],
            options={
                'verbose_name': 'Product Schedule',
                'verbose_name_plural': 'Product Schedules',
            },
        ),
        migrations.RemoveField(
            model_name='dynamicprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttimeslotprice',
            name='dynamicPrice',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='availability',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Attraction', 'Attraction ticket'), ('Tour', 'Tour'), ('City', 'City card'), ('Transfer', 'Transfer'), ('Rental', 'Rental'), ('Hop', 'Hop-on hop-off ticket')], max_length=22),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='DynamicPrice',
        ),
        migrations.DeleteModel(
            name='ProductTimeSlotPrice',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='productschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.productschedule'),
        ),
    ]
