# Generated by Django 4.2.6 on 2025-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_productprice_productschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='departure',
            new_name='departure_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountform',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retailprice',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], max_length=20),
        ),
    ]
