# Generated by Django 4.2.6 on 2025-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_rename_departure_booking_departure_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='test title', max_length=255),
            preserve_default=False,
        ),
    ]
