# Generated by Django 4.2.6 on 2025-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='departure_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
