# Generated by Django 5.1.6 on 2025-02-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_product_departure_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='languageType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
