# Generated by Django 5.1.6 on 2025-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_product_category_alter_product_languagetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isBlocked',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='hoponhopoffticket',
            name='routeInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bookingInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cancellationPolicy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contactInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='termsAndConditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='damagePolicy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour1',
            name='guideInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour1',
            name='locationsCovered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
