# Generated by Django 5.1.6 on 2025-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_rename_isblocked_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='e', upload_to='images/tours'),
            preserve_default=False,
        ),
    ]
