# Generated by Django 5.1.6 on 2025-02-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_remove_image_url_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('backgroundColor', models.CharField(max_length=50)),
                ('liteBg', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviewcards', to='shop.product')),
            ],
        ),
    ]
