# Generated by Django 5.1.6 on 2025-02-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_overviewcard1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basePriceFor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
