# Generated by Django 5.1.6 on 2025-02-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='overviewcard',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='price',
            name='option',
        ),
        migrations.RemoveField(
            model_name='price',
            name='tour',
        ),
        migrations.DeleteModel(
            name='SalePoint',
        ),
        migrations.DeleteModel(
            name='SearchCategory',
        ),
        migrations.RemoveField(
            model_name='tourimage',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='available_days',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='OverviewCard',
        ),
        migrations.DeleteModel(
            name='PriceOption',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourSchedule',
        ),
    ]
