# Generated by Django 5.1.6 on 2025-02-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_remove_tour_category_remove_overviewcard_tour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountForm',
        ),
        migrations.DeleteModel(
            name='RetailPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
