# Generated by Django 5.1.6 on 2025-02-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_delete_discountform_delete_retailprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
