# Generated by Django 5.1.6 on 2025-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_product_baseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
