# Generated by Django 5.1.6 on 2025-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_product_baseprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basePrice',
        ),
    ]
