# Generated by Django 5.1.6 on 2025-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_remove_product_baseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
