# Generated by Django 5.1.6 on 2025-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_product_baseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
