# Generated by Django 5.1.6 on 2025-02-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_booking_discount_percent_booking_gross_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_category', models.CharField(choices=[('G', 'GLT')], max_length=20)),
                ('product_id', models.CharField(max_length=255)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.CharField(blank=True, max_length=255, null=True)),
                ('product_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('product_location', models.CharField(blank=True, max_length=255, null=True)),
                ('product_price', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
