# Generated by Django 5.1.6 on 2025-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_rename_added_at_wishlistitem_created_at_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], default='g', max_length=20),
        ),
    ]
