# Generated by Django 5.1.6 on 2025-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_review_api_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='api_category',
            field=models.CharField(choices=[('G', 'GLT')], default='G', max_length=20),
        ),
    ]
