# Generated by Django 5.1.6 on 2025-02-28 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_review_api_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
        migrations.RemoveField(
            model_name='option',
            name='product',
        ),
        migrations.AddField(
            model_name='option',
            name='audio_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='booklet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='drop_off_type',
            field=models.CharField(choices=[('same_place', 'At the same place you meet them'), ('different_place', 'At a different place'), ('no_service', 'No drop-off service, the customer stays at the site or destination')], default='same_place', help_text='Specify the drop-off type for this option.', max_length=20),
        ),
        migrations.AddField(
            model_name='option',
            name='has_fixed_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='maximum_group_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='option',
            name='meeting_point_type',
            field=models.CharField(choices=[('set_meeting_point', 'They go to a set meeting point'), ('choose_meeting_point', 'They can choose where you pick them up from certain areas or a list of places')], default='set_meeting_point', help_text='Specify how the meeting point is determined.', max_length=20),
        ),
        migrations.AddField(
            model_name='option',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='skip_the_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='valid_for',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='AudioGuideLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_guides_languages', to='shop.option')),
            ],
        ),
        migrations.CreateModel(
            name='BookletLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_languages', to='shop.option')),
            ],
        ),
        migrations.CreateModel(
            name='DropOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drop', to='shop.option')),
            ],
        ),
        migrations.CreateModel(
            name='HostLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_languages', to='shop.option')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meet', to='shop.option')),
            ],
        ),
    ]
