# Generated by Django 5.1.6 on 2025-02-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_remove_option_name_remove_option_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='Ac', max_length=100),
            preserve_default=False,
        ),
    ]
