# Generated by Django 5.1.6 on 2025-02-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.option'),
        ),
    ]
